import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LanguageProvider with ChangeNotifier {
  Locale _locale = const Locale('vi');

  LanguageProvider() {
    _loadFromPrefs();
  }

  Locale get locale => _locale;

  final Map<String, Map<String, String>> _localizedValues = {
    'vi': {
      'app_name': 'ChiTieuPlus',
      'tab_home': 'Tổng quan',
      'tab_transactions': 'Giao dịch',
      'tab_budget': 'Ngân sách',
      'tab_report': 'Báo cáo',
      'tab_settings': 'Cài đặt',
      'detailed_report_title': 'Báo cáo chi tiết',
      'hello': 'Xin chào',
      'total_balance': 'Tổng số dư',
      'wallet': 'Ví của bạn',
      'wallet_demo': 'Ví của bạn (Demo)',
      'deposit_to_demo': 'Nạp vào Ví của bạn (Demo)',
      'ai_scan': 'AI QUÉT HÓA ĐƠN',
      'recent_transactions': 'Giao dịch gần đây',
      'view_all': 'Xem tất cả',
      'analysis': 'Phân tích chi tiêu',
      'last_7_days': '7 ngày qua',
      'category_breakdown': 'Cơ cấu chi tiêu',
      'search_placeholder': 'Tìm kiếm giao dịch...',
      'filter_all': 'Tất cả',
      'filter_income': 'Thu nhập',
      'filter_expense': 'Chi tiêu',
      'confirm_delete': 'Xác nhận xóa',
      'delete_msg': 'Bạn có chắc chắn muốn xóa giao dịch đã chọn?',
      'cancel': 'Hủy',
      'delete': 'Xóa',
      'settings_section_general': 'Chung',
      'settings_section_account': 'Tài khoản',
      'settings_section_about': 'Về ứng dụng',
      'settings_item_appearance': 'Giao diện',
      'settings_item_language': 'Ngôn ngữ',
      'settings_item_eye_protection': 'Bảo vệ mắt',
      'settings_item_notifications': 'Thông báo',
      'settings_item_security': 'Bảo mật',
      'settings_item_account_info': 'Thông tin cá nhân',
      'settings_item_link_bank': 'Liên kết ngân hàng',
      'settings_item_help': 'Trung tâm hỗ trợ',
      'settings_item_logout': 'Đăng xuất',
      'settings_appearance_dark_mode': 'Chế độ tối',
      'settings_appearance_light_mode': 'Chế độ sáng',
      'settings_language_vi': 'Tiếng Việt',
      'settings_language_en': 'English',
      'confirm_logout_title': 'Đăng xuất',
      'confirm_logout_message': 'Bạn có chắc chắn muốn đăng xuất không?',
      'confirm_logout_yes': 'Đăng xuất',
      'confirm_logout_no': 'Hủy',
      'login_title': 'Chào mừng trở lại',
      'login_subtitle': 'Đăng nhập vào tài khoản của bạn',
      'login_field_email': 'Email',
      'login_field_password': 'Mật khẩu',
      'login_button_forgot_password': 'Quên mật khẩu?',
      'login_button_signin': 'Đăng nhập',
      'login_divider_text': 'Hoặc tiếp tục với',
      'login_button_google': 'Google',
      'login_button_guest': 'Khách',
      'login_footer_text': 'Chưa có tài khoản?',
      'login_footer_link': 'Đăng ký ngay',
      'login_hint_email': 'ChitieuPlus@gmail.com',
      'login_hint_password': '••••••••',
      'login_error_invalid_email': 'Vui lòng nhập email hợp lệ',
      'login_error_empty_password': 'Mật khẩu không được để trống',
      'register_title': 'Tạo tài khoản',
      'register_subtitle': 'Bắt đầu hành trình quản lý tài chính của bạn',
      'register_field_fullname': 'Họ và tên',
      'register_field_confirm_password': 'Xác nhận mật khẩu',
      'register_button_signup': 'Đăng ký',
      'register_footer_text': 'Đã có tài khoản?',
      'register_footer_link': 'Đăng nhập',
      'register_hint_fullname': 'Nguyễn Văn A',
      'register_error_empty_fullname': 'Họ tên không được để trống',
      'register_error_password_mismatch': 'Mật khẩu xác nhận không khớp',
      'forgot_password_title': 'Quên mật khẩu',
      'forgot_password_subtitle': 'Nhập email của bạn để nhận mã xác minh',
      'forgot_password_button_send': 'Gửi mã xác minh',
      'forgot_password_footer_link': 'Quay lại đăng nhập',
      'forgot_password_error_email_sent': 'Mã xác minh đã được gửi',
      'otp_title': 'Xác minh OTP',
      'otp_subtitle': 'Vui lòng nhập mã OTP đã được gửi đến email của bạn',
      'otp_timer_prefix': 'Gửi lại mã sau ',
      'otp_timer_suffix': ' s',
      'otp_button_resend': 'Gửi lại mã',
      'otp_button_verify': 'Xác thực',
      'reset_password_title': 'Mật khẩu mới',
      'reset_password_subtitle': 'Tạo mật khẩu mới cho tài khoản của bạn',
      'reset_password_field_new': 'Mật khẩu mới',
      'reset_password_field_confirm': 'Xác nhận mật khẩu',
      'reset_password_button_submit': 'Đổi mật khẩu',
      'reset_password_button_back': 'Quay lại đăng nhập',
      'reset_password_validation_length': 'Ít nhất 8 ký tự',
      'reset_password_validation_mix': 'Bao gồm chữ cái và số',
      'reset_success_title': 'Thành công!',
      'reset_success_body':
          'Mật khẩu của bạn đã được thay đổi thành công. Bây giờ bạn có thể đăng nhập bằng mật khẩu mới.',
      'reset_success_button': 'Đăng nhập ngay',
      'add_transaction_title': 'Thêm giao dịch',
      'add_transaction_tab_manual': 'Thủ công',
      'add_transaction_tab_auto': 'Tự động (AI)',
      'add_transaction_amount_label': 'Số tiền giao dịch',
      'add_transaction_category_label': 'DANH MỤC',
      'add_transaction_date_label': 'NGÀY GIAO DỊCH',
      'add_transaction_note_label': 'GHI CHÚ',
      'add_transaction_note_hint': 'Nhập ghi chú tại đây...',
      'add_transaction_button_save': 'Lưu giao dịch',
      'add_transaction_button_scan': 'Quét hóa đơn (AI Scan)',
      'add_transaction_button_image': 'Nhập từ ảnh',
      'add_transaction_processing_ai': 'Đang phân tích ảnh...',
      'add_transaction_success_saved': 'Lưu giao dịch thành công!',
      'category_food': 'Ăn uống',
      'category_shopping': 'Mua sắm',
      'category_transport': 'Di chuyển',
      'category_bills': 'Hóa đơn',
      'category_entertainment': 'Giải trí',
      'category_health': 'Sức khỏe',
      'category_education': 'Giáo dục',
      'category_salary': 'Lương',
      'category_other': 'Khác',
      'notifications_title': 'Thông báo',
      'notifications_filter_all': 'Tất cả',
      'notifications_filter_transaction': 'Giao dịch',
      'notifications_filter_system': 'Hệ thống',
      'notifications_filter_ai': 'AI Nhắc nhở',
      'notifications_filter_security': 'Bảo mật',
      'notifications_empty_state': 'Không có dữ liệu',
      'notifications_action_mark_read': 'Đánh dấu đã đọc tất cả',
      'notifications_action_select': 'Chọn thông báo',
      'notifications_action_cancel': 'Hủy chọn',
      'onboarding_next': 'Tiếp tục',
      'onboarding_start': 'Bắt đầu ngay',
      'onboarding_skip': 'BỎ QUA',
      'onboarding_p2_title': 'Bạn tên là gì?',
      'onboarding_p2_subtitle':
          'Chào mừng đến với ChiTieuPlus. Hãy cho chúng tôi biết tên của bạn để bắt đầu hành trình quản lý tài chính.',
      'onboarding_p2_label': 'Họ và tên của bạn',
      'onboarding_p2_hint': 'Nhập tên đầy đủ...',
      'onboarding_p3_title': 'Chọn loại tiền tệ',
      'onboarding_p3_subtitle':
          'Chọn tiền tệ chính để theo dõi các khoản chi tiêu của bạn',
      'onboarding_terms_1': 'Bằng việc tiếp tục, bạn chấp thuận với ',
      'onboarding_terms_2': 'chính sách điều khoản',
      'onboarding_terms_3': ' và ',
      'onboarding_terms_4': 'quyền riêng tư',
      'onboarding_terms_5': ' của chúng tôi.',
      'onboarding_p1_welcome': 'Chào mừng đến\nvới\nChiTieuPlus',
      'onboarding_p1_feature1': 'Quản lý chi tiêu thông minh với AI',
      'onboarding_p1_feature2': 'Biểu đồ phân tích trực quan',
      'onboarding_p1_feature3': 'Sao lưu dữ liệu thời thực',
      'ocr_scan_title': 'Quét hóa đơn AI',
      'ocr_scan_hint': 'Đặt hóa đơn vào khung hình\nhoặc chọn từ thư viện',
      'ocr_scan_btn_take_photo': 'Chụp ảnh hóa đơn',
      'ocr_scan_btn_library': 'Chọn từ thư viện',
      'ocr_scan_processing': 'Đang phân tích hóa đơn...',
      'ocr_scan_ai_processing': 'Trí tuệ nhân tạo đang xử lý...',
      'ocr_scan_error_title': 'Lỗi AI Scan',
      'ocr_scan_error_not_recognized':
          'Không thể nhận diện được hóa đơn. Vui lòng thử lại.',
      'ocr_scan_prompt': '''
      Hãy đóng vai một chuyên gia kế toán. Tôi sẽ gửi cho bạn một ảnh hóa đơn. 
      Nhiệm vụ của bạn là trích xuất các thông tin sau dưới dạng JSON:
      - title: Tên cửa hàng hoặc nội dung chính của hóa đơn (Ví dụ: "Phở Lý Quốc Sư", "Siêu thị Winmart").
      - amount: Tổng số tiền thanh toán (chỉ lấy số).
      - category: Phân loại vào một trong các mục: Ăn uống, Mua sắm, Di chuyển, Hóa đơn, Giải trí, Sức khỏe, Giáo dục, Khác.
      - date: Ngày trên hóa đơn (định dạng YYYY-MM-DD). Nếu không thấy hãy để ngày hiện tại.
      - note: Ghi chú thêm nếu cần.

      Chỉ trả về JSON, không giải thích gì thêm.
      ''',
      'ai_chat_title': 'Trợ lý AI',
      'ai_chat_new_chat': 'Cuộc trò chuyện mới',
      'ai_chat_greeting':
          'Chào bạn, tôi là trợ lý ảo ChiTieuPlus. Tôi có thể giúp gì cho bạn hôm nay?',
      'ai_chat_hint_input': 'Hỏi tôi bất cứ điều gì...',
      'ai_chat_hint_offline': 'Vui lòng kiểm tra kết nối...',
      'ai_chat_hint_limit': 'AI đang bị giới hạn...',
      'ai_chat_hint_listening': 'Đang nghe...',
      'ai_chat_limit_reached':
          'Giới hạn API đã đạt cho Model này. Vui lòng chờ hoặc đổi sang Model khác.',
      'ai_chat_limit_timer_prefix': 'Giới hạn model đã đạt. Vui lòng chờ:',
      'ai_chat_switch_model': 'Đổi Model khác',
      'ai_chat_offline_msg': 'Đã mất kết nối mạng. AI đang ngoại tuyến.',
      'ai_chat_offline_badge': 'Ngoại tuyến',
      'ai_chat_typing': 'AI đang soạn câu trả lời...',
      'ai_chat_copy_tooltip': 'Sao chép',
      'ai_chat_copied_msg': 'Đã sao chép vào bộ nhớ tạm',
      'ai_chat_rename_title': 'Đổi tên cuộc trò chuyện',
      'ai_chat_rename_hint': 'Nhập tên mới...',
      'ai_chat_rename_save': 'Lưu',
      'ai_chat_rename_cancel': 'Hủy',
      'ai_chat_delete_session': 'Xóa hội thoại này',
      'ai_chat_delete_all_title': 'Xóa tất cả?',
      'ai_chat_delete_all_msg':
          'Hành động này sẽ xóa vĩnh viễn toàn bộ lịch sử trò chuyện.',
      'ai_chat_delete_all_btn': 'Xóa hết',
      'ai_chat_pin': 'Ghim cuộc trò chuyện',
      'ai_chat_unpin': 'Bỏ ghim',
      'ai_chat_rename_action': 'Đổi tên',
      'ai_chat_select_model_action': 'Chọn Model AI (v2+)',
      'ai_chat_model_selector_title': 'Chọn Phiên bản Gemini',
      'ai_chat_model_version_label': 'Phiên bản AI',
      'ai_chat_model_group_label': 'Thông tin phân nhóm',
      'ai_chat_model_current_prefix': 'Đang sử dụng model: ',
      'ai_chat_model_close': 'Đóng',
      'ai_chat_model_switched_msg': 'Đã chuyển sang phiên bản {version}',
      'ai_chat_url_dialog_title': 'URL trang web và YouTube',
      'ai_chat_url_dialog_subtitle':
          'Dán URL trang web và YouTube vào bên dưới để tải lên dưới dạng một nguồn.',
      'ai_chat_url_dialog_hint': 'Dán liên kết bất kỳ',
      'ai_chat_url_insert': 'Chèn',
      'ai_chat_url_note_1':
          'Để thêm nhiều URL, hãy phân tách bằng dấu cách hoặc dòng mới.',
      'ai_chat_url_note_2':
          'Hiện chỉ nhập được văn bản hiển thị trên trang web.',
      'ai_chat_url_note_3': 'Không hỗ trợ bài viết có tính phí.',
      'ai_chat_url_note_4':
          'Hiện chỉ nhập được bản chép lời của video trên YouTube.',
      'ai_chat_url_note_5': 'Chỉ hỗ trợ video công khai trên YouTube.',
      'ai_chat_mic_error': 'Không thể truy cập Micro. Vui lòng cấp quyền.',
      'ai_chat_website_btn': 'Trang web',
      'ai_chat_history_header': 'Lịch sử trò chuyện',
      'ai_chat_empty_header':
          'Hôm nay tôi có thể giúp gì cho tình hình tài chính của bạn?',
      'ai_chat_continue_header': 'Tiếp tục cuộc trò chuyện về ',
      'ai_chat_transaction_save_btn': 'Lưu giao dịch',
      'ai_chat_transaction_saved_badge': 'Đã lưu giao dịch',
      'ai_chat_transaction_confirm_badge': 'Xác nhận giao dịch',
      'ai_chat_transaction_trial_wallet': 'Nạp tiền từ Ví dùng thử',
      'ai_chat_transaction_content_label': 'Nội dung:',
      'ai_chat_transaction_amount_label': 'Số tiền:',
      'ai_chat_transaction_category_label': 'Hạng mục:',
      'ai_chat_transaction_save_success': 'Giao dịch đã được lưu!',
      'ai_chat_transaction_save_error': 'Lỗi khi lưu: ',
      'ai_chat_transaction_login_required':
          'Vui lòng đăng nhập để lưu giao dịch.',
      'ai_chat_transaction_notif_success_title': 'Giao dịch thành công',
      'ai_chat_transaction_notif_success_body':
          'Đã lưu "{title}" với số tiền {amount}đ',
      'ai_chat_transaction_notif_error_title': 'Giao dịch thất bại',
      'ai_chat_transaction_notif_error_body':
          'Không thể lưu giao dịch: {title}. Lỗi: {error}',
      'ai_chat_analyze_request': 'Hãy phân tích những nội dung này giúp tôi.',
      'ai_chat_analyze_content_placeholder': 'Phân tích nội dung',
      'ai_chat_time_now': 'Bây giờ',
      'details': 'Chi tiết',
      'ai_bubble_greeting':
          'Chào bạn! Tôi có thể giúp gì cho\nngân sách của bạn hôm nay?',
      'greeting_morning': 'Chào buổi sáng',
      'greeting_afternoon': 'Chào buổi trưa',
      'greeting_evening': 'Chào buổi chiều',
      'greeting_night': 'Chào buổi tối',
      'error_cannot_open_url': 'Không thể mở liên kết',
      'total': 'Tổng',
      'no_data': 'Không có dữ liệu',
      'export_preparing': 'Đang chuẩn bị dữ liệu {type}...',
      'export_success': 'Đã xuất database thành công: {file}',
      'export_downloading': 'Đang bắt đầu tải xuống: {file}',
      'export_error': 'Lỗi khi xuất database: {error}',
      'selected_count': 'Đã chọn {count}',
      'confirm_delete_msg_multiple':
          'Bạn có chắc chắn muốn xóa {count} giao dịch đã chọn?',
      'confirm_delete_msg_single': 'Giao dịch này sẽ bị xóa vĩnh viễn.',
      'delete_success_count': 'Đã xóa {count} giao dịch',
      'today': 'Hôm nay',
      'yesterday': 'Hôm qua',
      'this_week': 'Tuần này',
      'this_month': 'Tháng này',
      'custom': 'Tùy chỉnh',
      'search_transactions': 'Tìm kiếm giao dịch...',
      'pin': 'Ghim',
      'unpin': 'Bỏ ghim',
      'budget_screen_title': 'Màn hình Ngân sách',
      'report_screen_title': 'Màn hình Báo cáo',
      'spending_trends': 'Xu hướng chi tiêu',
      'category_breakdown_title': 'Cơ cấu chi tiêu',
      'chart_total': 'Tổng',
      'filter_today': 'Hôm nay',
      'filter_week': 'Tuần này',
      'filter_month': 'Tháng này',
      'filter_custom': 'Tùy chỉnh',
      'friendly_date_today': 'HÔM NAY, ',
      'friendly_date_yesterday': 'HÔM QUA, ',
      'month_format': 'THÁNG',
    },
    'en': {
      'app_name': 'ChiTieuPlus',
      'tab_home': 'Home',
      'tab_transactions': 'Transactions',
      'tab_budget': 'Budget',
      'tab_report': 'Report',
      'tab_settings': 'Settings',
      'detailed_report_title': 'Detailed Report',
      'hello': 'Hello',
      'total_balance': 'Total Balance',
      'wallet': 'Your Wallet',
      'wallet_demo': 'Your Wallet (Demo)',
      'deposit_to_demo': 'Deposit to Your Wallet (Demo)',
      'ai_scan': 'AI BILL SCAN',
      'recent_transactions': 'Recent Transactions',
      'view_all': 'View All',
      'analysis': 'Spending Analysis',
      'last_7_days': 'Last 7 Days',
      'category_breakdown': 'Category Breakdown',
      'search_placeholder': 'Search transactions...',
      'filter_all': 'All',
      'filter_income': 'Income',
      'filter_expense': 'Expense',
      'confirm_delete': 'Confirm Delete',
      'delete_msg': 'Are you sure you want to delete selected transactions?',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'settings_section_general': 'General',
      'settings_section_account': 'Account',
      'settings_section_about': 'About',
      'settings_item_appearance': 'Appearance',
      'settings_item_language': 'Language',
      'settings_item_eye_protection': 'Eye Protection',
      'settings_item_notifications': 'Notifications',
      'settings_item_security': 'Security',
      'settings_item_account_info': 'Account Info',
      'settings_item_link_bank': 'Link Bank Account',
      'settings_item_help': 'Help Center',
      'settings_item_logout': 'Logout',
      'settings_appearance_dark_mode': 'Dark Mode',
      'settings_appearance_light_mode': 'Light Mode',
      'settings_language_vi': 'Vietnamese',
      'settings_language_en': 'English',
      'confirm_logout_title': 'Logout',
      'confirm_logout_message': 'Are you sure you want to logout?',
      'confirm_logout_yes': 'Logout',
      'confirm_logout_no': 'Cancel',
      'login_title': 'Welcome Back',
      'login_subtitle': 'Login to your account',
      'login_field_email': 'Email',
      'login_field_password': 'Password',
      'login_button_forgot_password': 'Forgot Password?',
      'login_button_signin': 'Sign In',
      'login_divider_text': 'Or continue with',
      'login_button_google': 'Google',
      'login_button_guest': 'Guest',
      'login_footer_text': 'Don\'t have an account?',
      'login_footer_link': 'Register now',
      'login_hint_email': 'ChitieuPlus@gmail.com',
      'login_hint_password': '••••••••',
      'login_error_invalid_email': 'Please enter a valid email',
      'login_error_empty_password': 'Password cannot be empty',
      'register_title': 'Create Account',
      'register_subtitle': 'Start your financial management journey',
      'register_field_fullname': 'Full Name',
      'register_field_confirm_password': 'Confirm Password',
      'register_button_signup': 'Sign Up',
      'register_footer_text': 'Already have an account?',
      'register_footer_link': 'Login',
      'register_hint_fullname': 'John Doe',
      'register_error_empty_fullname': 'Full name cannot be empty',
      'register_error_password_mismatch': 'Passwords do not match',
      'forgot_password_title': 'Forgot Password',
      'forgot_password_subtitle':
          'Enter your email to receive verification code',
      'forgot_password_button_send': 'Send Verification Code',
      'forgot_password_footer_link': 'Back to Login',
      'forgot_password_error_email_sent': 'Verification code sent',
      'otp_title': 'OTP Verification',
      'otp_subtitle': 'Please enter the OTP code sent to your email',
      'otp_timer_prefix': 'Resend in ',
      'otp_timer_suffix': ' s',
      'otp_button_resend': 'Resend Code',
      'otp_button_verify': 'Verify',
      'reset_password_title': 'New Password',
      'reset_password_subtitle': 'Create a new password for your account',
      'reset_password_field_new': 'New Password',
      'reset_password_field_confirm': 'Confirm Password',
      'reset_password_button_submit': 'Reset Password',
      'reset_password_button_back': 'Back to Login',
      'reset_password_validation_length': 'At least 8 characters',
      'reset_password_validation_mix': 'Include letters and numbers',
      'reset_success_title': 'Success!',
      'reset_success_body':
          'Your password has been changed successfully. You can now login with your new password.',
      'reset_success_button': 'Login Now',
      'add_transaction_title': 'Add Transaction',
      'add_transaction_tab_manual': 'Manual',
      'add_transaction_tab_auto': 'Automatic (AI)',
      'add_transaction_amount_label': 'Transaction Amount',
      'add_transaction_category_label': 'CATEGORY',
      'add_transaction_date_label': 'TRANSACTION DATE',
      'add_transaction_note_label': 'NOTE',
      'add_transaction_note_hint': 'Enter note here...',
      'add_transaction_button_save': 'Save Transaction',
      'add_transaction_button_scan': 'Scan Receipt (AI Scan)',
      'add_transaction_button_image': 'Import from Image',
      'add_transaction_processing_ai': 'Analyzing image...',
      'add_transaction_success_saved': 'Transaction saved successfully!',
      'category_food': 'Food & Drink',
      'category_shopping': 'Shopping',
      'category_transport': 'Transportation',
      'category_bills': 'Bills',
      'category_entertainment': 'Entertainment',
      'category_health': 'Health',
      'category_education': 'Education',
      'category_salary': 'Salary',
      'category_other': 'Other',
      'notifications_title': 'Notifications',
      'notifications_filter_all': 'All',
      'notifications_filter_transaction': 'Transactions',
      'notifications_filter_system': 'System',
      'notifications_filter_ai': 'AI Reminders',
      'notifications_filter_security': 'Security',
      'notifications_empty_state': 'No data available',
      'notifications_action_mark_read': 'Mark all as read',
      'notifications_action_select': 'Select notifications',
      'notifications_action_cancel': 'Cancel selection',
      'onboarding_next': 'Next',
      'onboarding_start': 'Get Started',
      'onboarding_skip': 'SKIP',
      'onboarding_p2_title': 'What is your name?',
      'onboarding_p2_subtitle':
          'Welcome to ChiTieuPlus. Let us know your name to start your financial journey.',
      'onboarding_p2_label': 'Your Full Name',
      'onboarding_p2_hint': 'Enter full name...',
      'onboarding_p3_title': 'Choose Currency',
      'onboarding_p3_subtitle': 'Choose main currency to track your expenses',
      'onboarding_terms_1': 'By continuing, you agree to our ',
      'onboarding_terms_2': 'Terms of Service',
      'onboarding_terms_3': ' and ',
      'onboarding_terms_4': 'Privacy Policy',
      'onboarding_terms_5': '.',
      'onboarding_p1_welcome': 'Welcome to\nChiTieuPlus',
      'onboarding_p1_feature1': 'Smart spending management with AI',
      'onboarding_p1_feature2': 'Visual analysis charts',
      'onboarding_p1_feature3': 'Real-time data synchronization',
      'ocr_scan_title': 'AI Receipt Scan',
      'ocr_scan_hint': 'Place receipt in frame\nor select from library',
      'ocr_scan_btn_take_photo': 'Take a photo of receipt',
      'ocr_scan_btn_library': 'Select from library',
      'ocr_scan_processing': 'Analyzing receipt...',
      'ocr_scan_ai_processing': 'AI is processing...',
      'ocr_scan_error_title': 'AI Scan Error',
      'ocr_scan_error_not_recognized':
          'Could not recognize the receipt. Please try again.',
      'ocr_scan_prompt': '''
      Act as an accounting expert. I will send you an image of a receipt.
      Your task is to extract the following information in JSON format:
      - title: Store name or main content of the receipt (Example: "Starbucks", "Walmart").
      - amount: Total payment amount (number only).
      - category: Categorize into one of these: Food & Drink, Shopping, Transportation, Bills, Entertainment, Health, Education, Other.
      - date: Date on receipt (YYYY-MM-DD format). If not found, use today's date.
      - note: Additional notes if needed.

      Return ONLY JSON, no further explanation.
      ''',
      'ai_chat_title': 'AI Assistant',
      'ai_chat_new_chat': 'New Conversation',
      'ai_chat_greeting':
          'Hello, I am ChiTieuPlus virtual assistant. How can I help you today?',
      'ai_chat_hint_input': 'Ask me anything...',
      'ai_chat_hint_offline': 'Please check your connection...',
      'ai_chat_hint_limit': 'AI is being limited...',
      'ai_chat_hint_listening': 'Listening...',
      'ai_chat_limit_reached':
          'API limit reached for this Model. Please wait or switch to another Model.',
      'ai_chat_limit_timer_prefix': 'Model limit reached. Please wait:',
      'ai_chat_switch_model': 'Switch Model',
      'ai_chat_offline_msg': 'Network connection lost. AI is offline.',
      'ai_chat_offline_badge': 'Offline',
      'ai_chat_typing': 'AI is typing a response...',
      'ai_chat_copy_tooltip': 'Copy',
      'ai_chat_copied_msg': 'Copied to clipboard',
      'ai_chat_rename_title': 'Rename conversation',
      'ai_chat_rename_hint': 'Enter new name...',
      'ai_chat_rename_save': 'Save',
      'ai_chat_rename_cancel': 'Cancel',
      'ai_chat_delete_session': 'Delete this conversation',
      'ai_chat_delete_all_title': 'Delete all?',
      'ai_chat_delete_all_msg':
          'This action will permanently delete all chat history.',
      'ai_chat_delete_all_btn': 'Delete all',
      'ai_chat_pin': 'Pin conversation',
      'ai_chat_unpin': 'Unpin',
      'ai_chat_rename_action': 'Rename',
      'ai_chat_select_model_action': 'Select AI Model (v2+)',
      'ai_chat_model_selector_title': 'Select Gemini Version',
      'ai_chat_model_version_label': 'AI Version',
      'ai_chat_model_group_label': 'Tier Information',
      'ai_chat_model_current_prefix': 'Currently using model: ',
      'ai_chat_model_close': 'Close',
      'ai_chat_model_switched_msg': 'Switched to version {version}',
      'ai_chat_url_dialog_title': 'Website and YouTube URL',
      'ai_chat_url_dialog_subtitle':
          'Paste website and YouTube URLs below to upload as a source.',
      'ai_chat_url_dialog_hint': 'Paste any link',
      'ai_chat_url_insert': 'Insert',
      'ai_chat_url_note_1':
          'To add multiple URLs, separate them with spaces or newlines.',
      'ai_chat_url_note_2':
          'Currently, only visible text on the web page can be imported.',
      'ai_chat_url_note_3': 'Paid articles are not supported.',
      'ai_chat_url_note_4':
          'Currently, only YouTube video transcripts can be imported.',
      'ai_chat_url_note_5': 'Only public YouTube videos are supported.',
      'ai_chat_mic_error': 'Cannot access Microphone. Please grant permission.',
      'ai_chat_website_btn': 'Websites',
      'ai_chat_history_header': 'Chat History',
      'ai_chat_empty_header':
          'How can I help with your financial situation today?',
      'ai_chat_continue_header': 'Continue conversation about ',
      'ai_chat_transaction_save_btn': 'Save Transaction',
      'ai_chat_transaction_saved_badge': 'Transaction saved',
      'ai_chat_transaction_confirm_badge': 'Confirm transaction',
      'ai_chat_transaction_trial_wallet': 'Deposit from Trial Wallet',
      'ai_chat_transaction_content_label': 'Content:',
      'ai_chat_transaction_amount_label': 'Amount:',
      'ai_chat_transaction_category_label': 'Category:',
      'ai_chat_transaction_save_success': 'Transaction saved!',
      'ai_chat_transaction_save_error': 'Error saving: ',
      'ai_chat_transaction_login_required': 'Please login to save transaction.',
      'ai_chat_transaction_notif_success_title': 'Transaction Success',
      'ai_chat_transaction_notif_success_body':
          'Saved "{title}" with amount {amount}',
      'ai_chat_transaction_notif_error_title': 'Transaction Failed',
      'ai_chat_transaction_notif_error_body':
          'Cannot save transaction: {title}. Error: {error}',
      'ai_chat_analyze_request': 'Please analyze this content for me.',
      'ai_chat_analyze_content_placeholder': 'Analyze content',
      'ai_chat_time_now': 'Now',
      'details': 'Details',
      'ai_bubble_greeting': 'Hello! How can I help with\nyour budget today?',
      'greeting_morning': 'Good morning',
      'greeting_afternoon': 'Good afternoon',
      'greeting_evening': 'Good evening',
      'greeting_night': 'Good night',
      'error_cannot_open_url': 'Cannot open link',
      'total': 'Total',
      'no_data': 'No data available',
      'export_preparing': 'Preparing {type} data...',
      'export_success': 'Database exported successfully: {file}',
      'export_downloading': 'Starting download: {file}',
      'export_error': 'Error exporting database: {error}',
      'selected_count': 'Selected {count}',
      'confirm_delete_msg_multiple':
          'Are you sure you want to delete {count} selected transactions?',
      'confirm_delete_msg_single':
          'This transaction will be permanently deleted.',
      'delete_success_count': 'Deleted {count} transactions',
      'today': 'Today',
      'yesterday': 'Yesterday',
      'this_week': 'This Week',
      'this_month': 'This Month',
      'custom': 'Custom',
      'search_transactions': 'Search transactions...',
      'pin': 'Pin',
      'unpin': 'Unpin',
      'budget_screen_title': 'Budget Screen',
      'report_screen_title': 'Report Screen',
      'spending_trends': 'Spending Trends',
      'category_breakdown_title': 'Category Breakdown',
      'chart_total': 'Total',
      'filter_today': 'Today',
      'filter_week': 'This Week',
      'filter_month': 'This Month',
      'filter_custom': 'Custom',
      'friendly_date_today': 'TODAY, ',
      'friendly_date_yesterday': 'YESTERDAY, ',
      'month_format': 'MONTH',
    },
  };

  String translate(String key) {
    return _localizedValues[_locale.languageCode]?[key] ?? key;
  }

  String translateWithParam(String key, Map<String, String> params) {
    String t = translate(key);
    params.forEach((k, v) {
      t = t.replaceAll('{$k}', v);
    });
    return t;
  }

  String translateCategory(String category) {
    final Map<String, String> categoryToKey = {
      'Ăn uống': 'category_food',
      'Mua sắm': 'category_shopping',
      'Di chuyển': 'category_transport',
      'Hóa đơn': 'category_bills',
      'Giải trí': 'category_entertainment',
      'Sức khỏe': 'category_health',
      'Giáo dục': 'category_education',
      'Lương': 'category_salary',
      'Khác': 'category_other',
    };
    final key = categoryToKey[category] ?? 'category_other';
    return translate(key);
  }

  Future<void> setLanguage(String languageCode) async {
    _locale = Locale(languageCode);
    notifyListeners();
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('language_code', languageCode);
  }

  Future<void> _loadFromPrefs() async {
    final prefs = await SharedPreferences.getInstance();
    final code = prefs.getString('language_code') ?? 'vi';
    _locale = Locale(code);
    notifyListeners();
  }
}
