// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtZejb2lI_17GlMNjz0nRp5GCqxoKuwwI',
    appId: '1:971401377167:web:3fdda45472a9055962c7fa',
    messagingSenderId: '971401377167',
    projectId: 'chitieuplus-app',
    authDomain: 'chitieuplus-app.firebaseapp.com',
    storageBucket: 'chitieuplus-app.firebasestorage.app',
    measurementId: 'G-QG3QNCXFZ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUFZ6r7_d88iGwUrX4XJK_3wx7iiWgn2I',
    appId: '1:971401377167:android:5422cdf733d9bdb962c7fa',
    messagingSenderId: '971401377167',
    projectId: 'chitieuplus-app',
    storageBucket: 'chitieuplus-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS4r4yHFLG0sTIFw8-WJU1CyYCt4RNisg',
    appId: '1:971401377167:ios:9d6ab2a07d3e0f7062c7fa',
    messagingSenderId: '971401377167',
    projectId: 'chitieuplus-app',
    storageBucket: 'chitieuplus-app.firebasestorage.app',
    iosClientId: '971401377167-8iibu3pofmftlmdmncsl3stu2brbetbf.apps.googleusercontent.com',
    iosBundleId: 'com.example.chitieuPlus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCS4r4yHFLG0sTIFw8-WJU1CyYCt4RNisg',
    appId: '1:971401377167:ios:9d6ab2a07d3e0f7062c7fa',
    messagingSenderId: '971401377167',
    projectId: 'chitieuplus-app',
    storageBucket: 'chitieuplus-app.firebasestorage.app',
    iosClientId: '971401377167-8iibu3pofmftlmdmncsl3stu2brbetbf.apps.googleusercontent.com',
    iosBundleId: 'com.example.chitieuPlus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtZejb2lI_17GlMNjz0nRp5GCqxoKuwwI',
    appId: '1:971401377167:web:3128c1c9b553e97f62c7fa',
    messagingSenderId: '971401377167',
    projectId: 'chitieuplus-app',
    authDomain: 'chitieuplus-app.firebaseapp.com',
    storageBucket: 'chitieuplus-app.firebasestorage.app',
    measurementId: 'G-C4T4QYT7CQ',
  );
}
