import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:intl/intl.dart';
import 'package:animate_do/animate_do.dart';
import 'package:firebase_auth/firebase_auth.dart';
import '../providers/theme_provider.dart';
import '../providers/language_provider.dart';
import '../providers/user_provider.dart';
import '../providers/transaction_provider.dart';
import '../providers/notification_provider.dart';
import '../models/transaction_model.dart';
import '../models/notification_model.dart';

class PaymentDetailsScreen extends StatefulWidget {
  final double amount;

  const PaymentDetailsScreen({super.key, required this.amount});

  @override
  State<PaymentDetailsScreen> createState() => _PaymentDetailsScreenState();
}

class _PaymentDetailsScreenState extends State<PaymentDetailsScreen> {
  String? _selectedSource; // null means Trial Wallet, otherwise bank name
  bool _isProcessing = false;

  String _formatCurrency(double amount) {
    return '${NumberFormat('#,###', 'vi_VN').format(amount).replaceAll(',', '.')}đ';
  }

  Future<void> _handleConfirm() async {
    final transactionProvider = context.read<TransactionProvider>();
    final languageProvider = context.read<LanguageProvider>();
    final user = FirebaseAuth.instance.currentUser;

    if (user == null) return;

    setState(() => _isProcessing = true);

    // Show loading
    showDialog(
      context: context,
      barrierDismissible: false,
      builder: (context) => const Center(
        child: CircularProgressIndicator(color: Color(0xFFEC5B13)),
      ),
    );

    try {
      final walletName =
          _selectedSource ?? languageProvider.translate('wallet_demo');

      final tx = TransactionModel(
        id: '', // Generated by service
        userId: user.uid,
        title: 'Nạp tiền vào $walletName',
        amount: widget.amount,
        category: 'Nạp tiền',
        date: DateTime.now(),
        type: TransactionType.income,
        wallet: 'main',
        note: _selectedSource == null
            ? 'Nạp qua Ví dùng thử'
            : 'Nạp qua ngân hàng $_selectedSource',
      );

      await transactionProvider.addTransaction(tx);

      if (mounted) {
        // Add notification
        context.read<NotificationProvider>().addNotification(
          title: 'Nạp tiền thành công',
          body:
              'Bạn đã nạp thành công ${_formatCurrency(widget.amount)} vào $walletName',
          type: NotificationType.transaction,
        );

        // Close loading
        Navigator.pop(context);

        // Show success and go home
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Nạp tiền thành công!'),
            backgroundColor: Colors.green,
          ),
        );

        // Return to home (pop two screens: PaymentDetails and Deposit)
        Navigator.pop(context); // Pop PaymentDetails
        Navigator.pop(context); // Pop Deposit
      }
    } catch (e) {
      if (mounted) {
        Navigator.pop(context); // Close loading
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Có lỗi xảy ra: $e'),
            backgroundColor: Colors.red,
          ),
        );
      }
    } finally {
      if (mounted) setState(() => _isProcessing = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    final themeProvider = context.watch<ThemeProvider>();
    final languageProvider = context.watch<LanguageProvider>();
    final userProvider = context.watch<UserProvider>();
    final bankAccounts = userProvider.bankAccounts;

    return Scaffold(
      backgroundColor: themeProvider.backgroundColor,
      appBar: AppBar(
        title: Text(
          'Chi tiết thanh toán',
          style: TextStyle(
            color: themeProvider.foregroundColor,
            fontWeight: FontWeight.bold,
          ),
        ),
        backgroundColor: themeProvider.backgroundColor,
        elevation: 0,
        leading: IconButton(
          icon: Icon(
            Icons.arrow_back_ios_new_rounded,
            color: themeProvider.foregroundColor,
          ),
          onPressed: () => Navigator.pop(context),
        ),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(20),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            FadeInDown(
              duration: const Duration(milliseconds: 500),
              child: _buildTransactionCard(themeProvider, languageProvider),
            ),
            const SizedBox(height: 30),
            FadeInLeft(
              duration: const Duration(milliseconds: 500),
              delay: const Duration(milliseconds: 200),
              child: Text(
                'Nguồn tiền',
                style: TextStyle(
                  color: themeProvider.foregroundColor,
                  fontSize: 18,
                  fontWeight: FontWeight.bold,
                ),
              ),
            ),
            const SizedBox(height: 15),
            FadeInUp(
              duration: const Duration(milliseconds: 500),
              delay: const Duration(milliseconds: 400),
              child: _buildSourceSelection(
                themeProvider,
                languageProvider,
                bankAccounts,
              ),
            ),
          ],
        ),
      ),
      bottomNavigationBar: _buildBottomAction(themeProvider),
    );
  }

  Widget _buildTransactionCard(
    ThemeProvider themeProvider,
    LanguageProvider languageProvider,
  ) {
    return Container(
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: themeProvider.secondaryColor,
        borderRadius: BorderRadius.circular(24),
        border: Border.all(color: themeProvider.borderColor),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withValues(alpha: 0.1),
            blurRadius: 10,
            offset: const Offset(0, 4),
          ),
        ],
      ),
      child: Column(
        children: [
          _buildDetailRow(
            'Dịch vụ',
            'Nạp tiền vào Ví ChiTieuPlus',
            themeProvider,
          ),
          const Divider(height: 30, color: Colors.white10),
          _buildDetailRow(
            'Nguồn tiền',
            _selectedSource ?? 'Ví dùng thử (Demo)',
            themeProvider,
            valueColor: _selectedSource == null ? Colors.orange : Colors.blue,
          ),
          const Divider(height: 30, color: Colors.white10),
          _buildDetailRow(
            'Phí giao dịch',
            'Miễn phí',
            themeProvider,
            valueColor: Colors.green,
          ),
          const Divider(height: 40, color: Colors.white10),
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Text(
                'Tổng tiền',
                style: TextStyle(
                  color: themeProvider.foregroundColor.withValues(alpha: 0.7),
                  fontSize: 16,
                ),
              ),
              Text(
                _formatCurrency(widget.amount),
                style: const TextStyle(
                  color: Color(0xFFEC5B13),
                  fontSize: 24,
                  fontWeight: FontWeight.bold,
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }

  Widget _buildDetailRow(
    String label,
    String value,
    ThemeProvider themeProvider, {
    Color? valueColor,
  }) {
    return Row(
      mainAxisAlignment: MainAxisAlignment.spaceBetween,
      children: [
        Text(
          label,
          style: TextStyle(
            color: themeProvider.foregroundColor.withValues(alpha: 0.5),
            fontSize: 14,
          ),
        ),
        Expanded(
          child: Text(
            value,
            textAlign: TextAlign.right,
            style: TextStyle(
              color: valueColor ?? themeProvider.foregroundColor,
              fontSize: 15,
              fontWeight: FontWeight.w600,
            ),
          ),
        ),
      ],
    );
  }

  Widget _buildSourceSelection(
    ThemeProvider themeProvider,
    LanguageProvider languageProvider,
    List<String> bankAccounts,
  ) {
    return Column(
      children: [
        _buildSourceItem(
          title: 'Ví dùng thử',
          subtitle: 'Số dư vô hạn (Dành cho Demo)',
          icon: Icons.account_balance_wallet_rounded,
          color: Colors.orange,
          isSelected: _selectedSource == null,
          onTap: () => setState(() => _selectedSource = null),
          themeProvider: themeProvider,
        ),
        ...bankAccounts.map(
          (account) => _buildSourceItem(
            title: account,
            subtitle: 'Ngân hàng đã liên kết',
            icon: Icons.account_balance_rounded,
            color: Colors.blue,
            isSelected: _selectedSource == account,
            onTap: () => setState(() => _selectedSource = account),
            themeProvider: themeProvider,
          ),
        ),
      ],
    );
  }

  Widget _buildSourceItem({
    required String title,
    required String subtitle,
    required IconData icon,
    required Color color,
    required bool isSelected,
    required VoidCallback onTap,
    required ThemeProvider themeProvider,
  }) {
    return GestureDetector(
      onTap: onTap,
      child: Container(
        margin: const EdgeInsets.only(bottom: 12),
        padding: const EdgeInsets.all(16),
        decoration: BoxDecoration(
          color: isSelected
              ? color.withValues(alpha: 0.1)
              : themeProvider.secondaryColor,
          borderRadius: BorderRadius.circular(16),
          border: Border.all(
            color: isSelected ? color : themeProvider.borderColor,
            width: isSelected ? 2 : 1,
          ),
        ),
        child: Row(
          children: [
            Container(
              padding: const EdgeInsets.all(10),
              decoration: BoxDecoration(
                color: color.withValues(alpha: 0.1),
                shape: BoxShape.circle,
              ),
              child: Icon(icon, color: color, size: 24),
            ),
            const SizedBox(width: 16),
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    title,
                    style: TextStyle(
                      color: themeProvider.foregroundColor,
                      fontSize: 16,
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                  Text(
                    subtitle,
                    style: TextStyle(
                      color: themeProvider.foregroundColor.withValues(
                        alpha: 0.5,
                      ),
                      fontSize: 12,
                    ),
                  ),
                ],
              ),
            ),
            if (isSelected)
              Icon(Icons.check_circle_rounded, color: color)
            else
              Icon(
                Icons.circle_outlined,
                color: themeProvider.foregroundColor.withValues(alpha: 0.2),
              ),
          ],
        ),
      ),
    );
  }

  Widget _buildBottomAction(ThemeProvider themeProvider) {
    return Container(
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: themeProvider.backgroundColor,
        boxShadow: [
          BoxShadow(
            color: Colors.black.withValues(alpha: 0.2),
            blurRadius: 20,
            offset: const Offset(0, -5),
          ),
        ],
      ),
      child: SafeArea(
        child: FadeInUp(
          duration: const Duration(milliseconds: 500),
          child: Container(
            width: double.infinity,
            height: 60,
            decoration: BoxDecoration(
              gradient: const LinearGradient(
                colors: [Color(0xFFEC5B13), Color(0xFFFF8C42)],
              ),
              borderRadius: BorderRadius.circular(30),
              boxShadow: [
                BoxShadow(
                  color: const Color(0xFFEC5B13).withValues(alpha: 0.3),
                  blurRadius: 15,
                  offset: const Offset(0, 8),
                ),
              ],
            ),
            child: InkWell(
              onTap: _isProcessing ? null : _handleConfirm,
              borderRadius: BorderRadius.circular(30),
              child: Center(
                child: _isProcessing
                    ? const CircularProgressIndicator(color: Colors.black)
                    : const Text(
                        'Xác nhận',
                        style: TextStyle(
                          color: Colors.black,
                          fontSize: 18,
                          fontWeight: FontWeight.bold,
                        ),
                      ),
              ),
            ),
          ),
        ),
      ),
    );
  }
}
